
$(function(){$('#login').click(login);$('#register').click(register);$('#logout').click(logout);$('#manage').click(view_manage);$('#message').click(view_message);$('.join_up').click(join_up);$("#applyAddress").click(changeApplyAddress);$("#applyAddress").mouseleave(changeApplyAddressMouse);});function changeApplyAddress(){var eleA=$("#applyAddress");if(eleA.val().length==0){eleA.val('http://');}}
function changeApplyAddressMouse(){var eleA=$("#applyAddress");if(eleA.val()=='http://'){eleA.val('');}}
function join_up(){if(!youtu.is_login){pt.setParams({"appid":1600000118,"daid":325,"s_url":"http://open.youtu.qq.com/welcome/logged_in","style":20,"protocol":"http:","domain":"qq.com","border_radius":1,"target":"top","maskOpacity":40});pt.showPtui();$.cookie('registerLogin',"1");return;}
    if(youtu.is_verify){window.location.href="../../welcome/create_app.html";}else{verify_email('暂不验证');return;}}
function view_message(){if(!youtu.is_login){$.dialog.alert("请先登录");return;}
    if(youtu.is_login){window.location.href="../../welcome/message.html";}else{$.dialog("请先登录");}}
function view_manage(){if(!youtu.is_login){$.dialog.alert("请先登录");return;}
    if(youtu.is_verify){window.location.href="../../soft_ctl/view_all_app.html";}else{verify_email("暂不验证");return;}}
function verify_email(tip){tip=tip||"本次登陆不再提醒";$.dialog.confirm("你还没有验证邮箱，是否现在验证？",{text:"好的",func:function(){window.location.href="../../welcome/mail.html";}},{text:tip,func:function(){$.cookie("not_remind_email","true");}});}
$(function(){$("#copyright").text("Copyright   © 1998-"+new Date().getUTCFullYear()+" Tencent.  All Rights Reserved");if(youtu.is_login){if($.cookie('registerLogin')=='1'){if(!youtu.is_verify){verify_email('暂不验证');}
    $.cookie('registerLogin','0');}}});function login(){pt.setParams({"appid":1600000118,"daid":325,"s_url":"http://open.youtu.qq.com/welcome/logged_in","style":20,"protocol":"http:","domain":"qq.com","border_radius":1,"target":"top","maskOpacity":40});pt.showPtui();$.cookie('registerLogin',"1");}
function register(){pt.setParams({"appid":1600000118,"daid":325,"s_url":"http://open.youtu.qq.com/welcome/logged_in/true","style":20,"protocol":"http:","domain":"qq.com","border_radius":1,"target":"top","maskOpacity":40});pt.showPtui();}
function logout(){pt.logout(function(res){if(res===2){$.ajax({type:'POST',dataType:"json",url:'/user_ctl/log_out',error:function(){$.dialog.alert("网络异常，请稍后再试！");}});$.cookie('registerLogin','0');window.location.href="http://micioe.com/micioe/1.html";}});}
var getCookie=function(n){var m=document.cookie.match(new RegExp("(^| )"+n+"=([^;]*)(;|$)"));return!m?"":decodeURIComponent(m[2]);};$.fn.extend({shine:function(callback){var self=this;$(this).hide();setTimeout(function(){$(self).fadeIn(50);},80);setTimeout(function(){$(self).fadeOut(50);},160);setTimeout(function(){$(self).fadeIn(50);},240);setTimeout(function(){callback&&callback.call(self);},300);return $(this);},form:function(options){options=options||{};$(this).html5Validate(function(){var button=$(this).find("input[type=submit]").attr("disabled","disabled");$.ajax({url:$(this).attr("action"),type:$(this).attr("method")||"GET",data:$(this).serialize(),dataType:"json",success:function(json){$.jsonHandle(json);button.removeAttr("disabled");},error:function(){$.dialog.alert("网络异常，您可以稍后重试。");button.removeAttr("disabled");}});},{validate:options.validate});}});$.fn.getObjColor=function(objName){var rgb=$(this).css(objName);if($.browser.msie&&$.browser.version<9.0){return rgb;}else{rgb=rgb.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);function hex(x){return("0"+parseInt(x).toString(16)).slice(-2);}
    rgb="#"+hex(rgb[1])+hex(rgb[2])+hex(rgb[3]);}
    return rgb;};$.hex2RGB=function(hex){var sColor=hex.toLowerCase();var reg=/^#([0-9a-fA-f]{3}|[0-9a-fA-f]{6})$/;if(sColor&&reg.test(sColor)){if(sColor.length===4){var sColorNew="#";for(var i=1;i<4;i+=1){sColorNew+=sColor.slice(i,i+1).concat(sColor.slice(i,i+1));}
    sColor=sColorNew;}
    var sColorChange=[];for(var i=1;i<7;i+=2){sColorChange.push(parseInt("0x"+sColor.slice(i,i+2)));}
    return sColorChange;}else{return sColor;}};$.toHexColor=function(rgb){function hex(x){return("0"+parseInt(x).toString(16)).slice(-2);}
    rgb="#"+hex(rgb[0])+hex(rgb[1])+hex(rgb[2]);return rgb;};$.isIE=function(ver){var b=document.createElement('b')
    b.innerHTML='<!--[if IE '+ver+']><i></i><![endif]-->'
    return b.getElementsByTagName('i').length===1;},$.encodeParam=function(param,key){var paramStr="";if(param instanceof String||param instanceof Number||param instanceof Boolean){paramStr+="&"+key+"="+param;}else{$.each(param,function(i){var k=key==null?i:key+(param instanceof Array?"["+i+"]":"."+i);paramStr+='&'+$.encodeParam(this,k);});}
    return paramStr.substr(1);},$.dialog=(function(){var _create=function(content,ensure,cancel){var $container=$('<div class="dialog"></div>'),$body=$('<div class="dialog-body"></div>'),$footer=$('<div class="dialog-footer"></div>'),$title=$(),$ensure=null,$cancel=null;var htmlValign='<i class="dib-vm"></i>';if(typeof content=="object"){var $title=$('<div class="dialog-title">'+(content.title||"")+'</div>');var $content=$('<div class="dialog-content">'+content.content+'</div>');ensure=ensure||content.ensure;cancel=cancel||content.cancel;}else if(typeof content=="string"){$content=$('<div class="dialog-main"><span class="dialog-main-align">'+content+'</span>'+htmlValign+'</div>');}
    if(ensure){ensure.type="ensure";$ensure=_button(ensure,$container);$footer.append($ensure);}
    if(cancel){cancel.type="cancel";$cancel=_button(cancel,$container);$footer.append($cancel);}
    if(!ensure&&!cancel)$footer.hide();$body.append($title).append($content).append($footer);$container.append($body).append($(htmlValign));$(document.body).append($container);if($ensure&&$ensure.length)$ensure.get(0).focus();$container.$body=$body;$container.$footer=$footer;$container.$title=$title;$container.$ensure=$ensure;$container.$cancel=$cancel;return $container;};var _button=function(data,container){if(!data)return $();var defaults={ensure:"好的",cancel:"取消"};data.type=data.type||"ensure";return $('<a href="javascript:" class="dialog-btn dialog-btn-'+data.type+'">'+(data.text||defaults[data.type])+'</a>').on("click",function(){if(data.func){data.func.call(this);}
    container.remove();container=null;});};return{open:function(content,options){options=options||{};if(!content)return $();if(content.size&&content.size()){content=content.get(0).outerHTML;}
    options.content=content;return _create(options);},alert:function(message,ensure){if(!ensure&&ensure!==null)ensure={};return _create(message,ensure);},confirm:function(message,ensure,cancel){if(!ensure&&ensure!==null)ensure={};if(!cancel&&cancel!==null)cancel={};return _create(message,ensure,cancel);}}})();$.jsonHandle=function(json){if(typeof json!="object")return;if(json.succ){if(typeof json.url=="string"){setTimeout(function(){location.href=json.url;},json.delay||0);}
    if(json.msg){var dialog=$.dialog.alert(json.msg,{text:json.text,func:function(){if(typeof json.url=="string")location.href=json.url;if(json.callback)json.callback(json);}});if(json.delay){setTimeout(function(){dialog&&dialog.$ensure.trigger("click");},json.delay||0);}}}else{$.dialog.alert(json.msg||"抱歉，没有操作成功，您可以刷新重试。");}};$.gototop=function(){$(document.body).append('');var gotop=$("#gotop").click(function(event){$(window).scrollTop(0);event.preventDefault();$(window).trigger("scroll");});$(window).scroll(function(){if($(this).scrollTop()==0){gotop.hide();}else{gotop.show();}});if(!window.addEventListener){$(window).resize(function(){if($(this).width()<1286){gotop.css("right",0);}else{gotop.css("right","auto");}});}};var YTUI={home:(function(){var exports={};exports.slide=function(options){options=options||{};var currentIndex=options.index||0,slideTimer=null,fadeoutTimer=null,slide=options.container||$("#slide"),slideX=options.list||$(".slideX"),dots=options.dots||$(".slideDot");var length=slideX.length,time=options.time||0,target=$();if(length<=1||slide.length*dots.length==0)return this;var disabled=false;var _next=function(){currentIndex++;if(currentIndex>=length)currentIndex=0;_fade();},_prev=function(){currentIndex--;if(currentIndex<0)currentIndex=length-1;_fade();},_fade=function(){disabled=true;target.fadeOut(function(){$(this).find(".slide-opacity").each(function(){$(this).css({opacity:0.0});});$(this).find(".slide-gif").each(function(){$(this).css('display',"none");});});target.find(".slide-opacity").stop(true);target=slideX.eq(currentIndex).fadeIn(function(){$(this).find(".slide-gif").each(function(index){$(this).css('display',"block");var url=$(this).css("backgroundImage");url=url.replace(/time=[0-9]{0,}/,"time="+Math.floor(Math.random()*1000000));$(this).css('backgroundImage',url);});$(this).find(".slide-opacity").each(function(index){var self=$(this);var start=self.data()["delay"];var duration=self.data()["duration"];self.delay(start).fadeIn().animate({opacity:1.0,},duration,function(){});});})
    _btn();},_btn=function(){dots.removeClass("active");dots.eq(currentIndex).addClass("active");};var _step=function(){_next();if(time){slideTimer=setTimeout(function(){_step();},time);}};slide.hover(function(){_btn();clearTimeout(slideTimer);},function(){if(time){slideTimer=setTimeout(function(){_step();},time);}});$(".slideDot").each(function(index,element){$(this).on("click",function(){if($(this).hasClass("active"))return;currentIndex=index;_fade();});});if(time){slideTimer=setTimeout(function(){_step();},time);}
    _fade();if(document.addEventListener)document.addEventListener("webkitvisibilitychange",function(){if(document.webkitHidden==false){clearTimeout(slideTimer);_step();}});};exports.whyUs=function(){if(typeof history.pushState=="undefined"){var whyUs=$("#whyUs"),whyUsA=whyUs.find("a");whyUsA.css("top",-500);whyUs.hover(function(){whyUsA.animate({top:-20},200);},function(){whyUsA.animate({top:-500},200);});}};exports.initTopBar=function(){var currentSel=window.YTUI.index;var currentItem=$(".navigation-v3 ul").children()[currentSel];$(currentItem).addClass('nav-up-selected');var imgBlock=$(currentItem).find(".navigation-up-item-block-img");imgBlock.css("display","block");};exports.updateNews=function(){var news_index=0;var nextNews=function(){news_index++;if(news_index>=$("ul#home-news-ul > li").length){news_index=0;}
    $("ul#home-news-ul").animate({"margin-top":-news_index*$("ul#home-news-ul > li").first().height()},500);}
    var newsTimer=setInterval(nextNews,3000);}
    return exports;})(),product:(function(index){var demos={demoInit:function(){DemoManager=$.extend(DemoManager,{demoImages:$(".product-picwall-content > ul > li"),imageView:$(".image-container"),localImageInput:$("#fileImage"),remoteImageInput:$("#url-image-btn"),requestView:$(".request"),responseView:$(".response")});},faceDetectInit:function(){this.demoInit();DemoManager=DemoManager.createFaceDetectManger();},faceLocationInit:function(){this.demoInit();DemoManager=DemoManager.createFaceLocationManager();},faceVerityInit:function(){this.demoInit();DemoManager=$.extend(DemoManager,{imageViewRight:$(".image-container-right"),localImageInputRight:$("#fileImageRight"),remoteImageInputRight:$("#url-image-btn-right"),verifyButton:$(".face-verify-button")});DemoManager=DemoManager.createFaceVerifyManager();},faceRecognizeInit:function(){this.demoInit();DemoManager=DemoManager.createFaceRecognizeManager();},imageRecognizeInit:function(){this.demoInit();DemoManager=DemoManager.createImageRecognizeManager();},};var pic_prev=$(".product-picwall-prev-button");var pic_next=$(".product-picwall-next-button");var pic_wall=$(".product-picwall-content");var pic_ul=$(".product-picwall-content ul");pic_ul.offX=0;var resize=function(){var wallWidth=pic_wall.innerWidth();var ulWidth=pic_ul.outerWidth();if(wallWidth>ulWidth){pic_ul.offX=0;}else{pic_ul.offX=Math.max(pic_ul.offX,(wallWidth-ulWidth)/2);pic_ul.offX=Math.min(pic_ul.offX,(ulWidth-wallWidth)/2);}
    var left=(wallWidth-ulWidth)/2-pic_ul.offX;if(ulWidth>wallWidth){pic_prev.css({display:"block"});pic_next.css({display:"block"});}else{pic_prev.css({display:"none"});pic_next.css({display:"none"});}
    pic_ul.css({display:"inline-block",position:"relative",left:left,});};$(window).resize(resize);resize();var interval;pic_prev.mouseenter(function(){interval=setInterval(function(){var wallWidth=pic_wall.innerWidth();var ulWidth=pic_ul.outerWidth();if(pic_ul.offX>(wallWidth-ulWidth)/2){pic_ul.offX--;resize();}},10);});pic_prev.mouseleave(function(){clearInterval(interval);});pic_next.mouseenter(function(){interval=setInterval(function(){var wallWidth=pic_wall.innerWidth();var ulWidth=pic_ul.outerWidth();if(pic_ul.offX<(ulWidth-wallWidth)/2){pic_ul.offX++;resize();}},10);});pic_next.mouseleave(function(){clearInterval(interval);});$(".product-experience-demo-url-field-tips").each(function(){$(this).click(function(){$(this).css("display","none");var parent=$(this).parent();parent.find("input").focus();});});$(".product-experience-demo-url-field").each(function(){$(this).focus(function(){var parent=$(this).parent();parent.find(".product-experience-demo-url-field-tips").css("display","none");});});$(".product-experience-demo-url-field").each(function(){$(this).blur(function(){var empty=$(this).val().length;if(empty==0){var parent=$(this).parent();parent.find(".product-experience-demo-url-field-tips").css("display","block");}});});$(".analysisBtn").on("click",function(){var img_url=$(".url-field").val();var img=new Image();img.src=img_url;if(img.complete){alert('from:complete : width:'+img.width+',height:'+img.height);var width=img.width;var height=img.height;if(width>468||height>468){var max_len=Math.max(width,height);var ratio=460.0/max_len;width=width*ratio;height=height*ratio;}
    var xoffset=(468.0-width)/2.0;var yoffset=(468.0-height)/2.0;$(".image-container").css("left",xoffset);$(".image-container").css("top",yoffset);$(".image-container").css("width",width);$(".image-container").css("height",height);$(".image-container").css("background-image","url("+img_url+")");$(".image-container").css("display","block");}else{img.onload=function(){alert('from:onload : width:'+img.width+',height:'+img.height);var width=img.width;var height=img.height;if(width>468||height>468){var max_len=Math.max(width,height);var ratio=460.0/max_len;width=width*ratio;height=height*ratio;}
    var xoffset=(468.0-width)/2.0;var yoffset=(468.0-height)/2.0;$(".image-container").css("left",xoffset);$(".image-container").css("top",yoffset);$(".image-container").css("width",width);$(".image-container").css("height",height);$(".image-container").css("background-image","url("+img_url+")");$(".image-container").css("display","block");};}});return demos;})(),check:function(){$("#applyForm").form({validate:function(){var checkPlatform=$("#applyPaltform .abs-clip:checked");if(checkPlatform.length==0){$("#applyPaltform .checkbox").eq(0).testRemind("至少选择一种应用平台");return false;}
    if((unpublish.prop("checked")&&!uploadLabel.data("succ"))){uploadLabel.testRemind("您尚未上传测试包");return false;}else if(publish.prop("checked")&&$.trim(eleAddress.val())==""){eleAddress.testRemind("请输入完整的应用地址").get(0).focus();return false;}
    return true;}});var eleAddress=$("#applyAddress");var funPlaceholder=function(value){eleAddress.attr("placeholder",value);if(eleAddress.data("target")){eleAddress.data("target").html(value);}};var publish=$("#publish"),unpublish=$("#unpublish"),applyUpload=$("#applyUpload");$.each([publish,unpublish],function(index,$target){$target.on("click",function(){if(index==0){applyUpload["addClass"]("dn");funPlaceholder("请填写网站地址或者真实的APP链接");}else{applyUpload["removeClass"]("dn");funPlaceholder("选填");}});});var uploadLabel=$("#labelUpload"),uploadForm=$("#uploadForm");var uploadFile=$("#uploadFile").change(function(){var arrName=$(this).val().split("\\"),name=arrName[arrName.length-1];if(name=="")return;if(/\.(?:ipa|apk)$/i.test(name)){uploadForm.length&&uploadForm.get(0).submit();uploadLabel.addClass("loading").data("name",name);}else{$.dialog.alert("只能上传ipa, apk格式的文件！");}});$("#uploadTrg").load(function(){var name=uploadLabel.data("name"),iframe=this;if(!name)return;var doc=iframe.contentDocument?iframe.contentDocument:frames[iframe.id].document;var response=doc.body&&doc.body.innerHTML;if(response&&response.startsWith('{')){response=$.parseJSON(response);}else{response={"succ":false,"msg":"上传出现异常，您可以稍后重试！"};}
    $.jsonHandle(response);uploadLabel.removeClass("loading").data("succ",response.succ);if(response.succ){uploadLabel.html(name).attr("title",name);}else{uploadLabel.html("重新上传").attr("title","");uploadForm.length&&uploadForm.get(0).reset();}});},myapp:function(){$(".myappView").each(function(index,element){$(this).on("click",function(){var softid=$(this).attr("softid");var submit_href=$(this).prev("a").attr("href");$.ajax({type:'POST',dataType:"json",url:window.ajaxUrlView||'/soft_ctl/get_one_app',data:"softid="+softid,success:function(data){if(!data.ret){$.dialog.alert(data.msg);return;}
    var softStatus=window.softStatus||{};var softType=window.softType||{};var finalPlatForm=[];data.platform&1?finalPlatForm.push('Web'):null;data.platform&2?finalPlatForm.push('IOS'):null;data.platform&4?finalPlatForm.push('Android'):null;data.platform&8?finalPlatForm.push('其他'):null;var content='<div class="apply-dialog-x">\
       <div class="fix"><span class="l">AppID：</span>'+(data.appid||"-")+'</div>\
       <div class="fix nowrap"><span class="l">SecretID：</span><span id="reset_secret_div">'+(data.secretid||"-")+'</span><a href="javascript:;" id="reset_secret" class="abs ml5"></a></div>\
       <div class="fix"><span class="l">SecretKey：</span>'+(data.secretkey||"-")+'</div>\
       <div class="fix"><span class="l">创建时间：</span>'+(data.createtime||"-")+'</div>\
       <div class="fix"><span class="l">应用描述：</span><div class="cell">'+(data.description||"-")+'</div></div>\
       <div class="fix"><span class="l">应用类型：</span>'+(softType[data.softtype]||"-")+'</div>\
       <div class="fix"><span class="l">应用平台：</span>'+(finalPlatForm.join(",")||"-")+'</div>\
       '+(data.status=="4"?'<div class="fix"><span class="l">未通过原因：</span><div class="cell">'+(data.reason||"-")+'</div></div>':'')+'\
       </div>';var options={title:data.name},self=$(this);options.ensure={text:"确定"};$.dialog.open(content,options);$('#reset_secret').click(softid,reset_secret);},error:function(){$.dialog.alert("网络异常，您可以稍后重试。");}});});});$(".myappRemove").each(function(index){$(this).attr({"data-ensure":"删除"}).data("callback",function(data){if(data.succ){$(this).parents("table").fadeOut(function(){$(this).remove();if($(".myappRemove").length==0){$("#myappNull").show();}});}});});},message:function(){var msgTable=$("#msgTable"),isFirst=true;$("#msgMore").data("callback",function(json){var number=$(this).attr("data-number");if(!json||!number)return;if(json.data&&json.data.length){var append=$('<div class="h0 ovh"></div>').html($.map(json.data,function(obj){return'<ul class="table-row">\
       <li class="table-cell col1">\
        <p>'+obj.title+'</p>\
        <p>'+obj.content+'</p>\
       </li>\
       <li class="table-cell col2">'+obj.createtime+'</li>\
      </ul>';}).join(""));if(isFirst){append.height(msgTable.find(".loading").outerHeight());msgTable.empty();}
    append.appendTo(msgTable).animate({height:append.get(0).scrollHeight},250,function(){msgTable.toggleClass("z");});}else if(isFirst){msgTable.find(".loading").removeClass("loading").html('目前还没有任何消息。');}
    if(isFirst)$(this).show();if(json.new_url)$(this).attr("data-url",json.new_url);if(!json.data||json.data.length<number){var parent=$(this).parent().html('<span class="gray">已无更多消息</span>');setTimeout(function(){parent.animate({opacity:0},350);},5000);}
    isFirst=false;});},api:function(){var sldeApi=$("#sideApi"),eleApi=sldeApi.find("a").eq(0),top=sldeApi.position().top;var h34=$("h2[id], h3[id], h4[id]");var arr_h34=$.map(h34,function(ele){return $(ele).position().top;});$("#faceApi").click(function(){$("#faceContect").toggleClass("open");$("#arrowface").toggleClass("open");});$("#face1").click(function(){$("#face1Content").toggleClass("open");$("#arrow1").toggleClass("open");});$("#face2").click(function(){$("#face2Content").toggleClass("open");$("#arrow2").toggleClass("open");});$("#face3").click(function(){$("#face3Content").toggleClass("open");$("#arrow3").toggleClass("open");});$("#face4").click(function(){$("#face4Content").toggleClass("open");$("#arrow4").toggleClass("open");});$("#imageApi").click(function(){$("#imageContent").toggleClass("open");$("#arrowApi").toggleClass("open");});},about:function(){var slide=$("#newsSlide");var width_slide=slide.width();var html_init=$.trim(slide.html());slide.html(html_init+html_init);var left=0;setInterval(function(){left=left-1;if(left<-1*width_slide){left=0;}
    window.addEventListener?slide.css({msTransform:"translateX("+left+"px)",webkitTransform:"translateX("+left+"px)",transform:"translateX("+left+"px)"}):slide.css({left:left});},33);},headerNav:function(){$('[_t_nav]').hover(function(){var _nav=$(this).attr('_t_nav');$('[_t_nav]').each(function(){if(_nav===$(this).attr('_t_nav')){$(this).addClass('nav-up-selected');var upItem=$(this).hasClass("nav-down-menu");if(!upItem){var imgBlock=$(this).find(".navigation-up-item-block-img");imgBlock.css("display","block");var normal=$(this).find("a").addClass("navigation-up-text-normal");if(normal){$(this).find("a").removeClass("navigation-up-text-normal");$(this).find("a").addClass("navigation-up-text-hovered");}}else{$('#'+_nav).css("display","block");}}});var tagName=$(this)[0].tagName;var xpos=$(this).position().left;if(tagName=="LI"||tagName=="li")
{var parent=$('#'+_nav).parent();parent.css({'left':xpos});}},function(){var _nav=$(this).attr('_t_nav');$('#'+_nav).css("display","none");$('[_t_nav]').each(function(){var hovered=$(this).hasClass('nav-up-selected');var selected=$(this).find("a").hasClass("navigation-up-text-selected");if(hovered&&(!selected)){$(this).removeClass('nav-up-selected');var imgBlock=$(this).find(".navigation-up-item-block-img");imgBlock.css("display","none");$(this).find("a").removeClass("navigation-up-text-hovered");$(this).find("a").addClass("navigation-up-text-normal");}});});$(function(){$(window).scroll(function(){if(window.YTUI.index==0){var vtop=$(document).scrollTop();if(vtop>200){$(".header").css("background","background: #08112e");$(".nav-down-menu").css("background","url(/content/img/navibar_2bk_darkblue.png)");}else{$(".header").css("background","url(/content/img/navibar_bk_black.png)");$(".nav-down-menu").css("background","url(/content/img/navibar_2bk_gray.png)");}}});});}};$(function(){if(!window.addEventListener){$(document.body).delegate("input","click",function(){var type=$(this).attr("type"),name=$(this).attr("name");if(type=="checkbox"){$(this)[$(this).prop("checked")?"addClass":"removeClass"]("checked").parent().toggleClass("z");}else if(type=="radio"){$("input[name="+name+"]").each(function(index,element){if(this.type=="radio"){$(this)[$(this).prop("checked")?"addClass":"removeClass"]("checked").parent().toggleClass("z");}});}});}
    if(!history.pushState){$("[placeholder]").each(function(index,element){var str="placeholder",placeholder=$(this).attr(str),id=element.id;if(!id){id=str+new Date().getTime();element.id=id;}
        var $label=$('<label class="'+str+'" for='+id+'>'+placeholder+'</label>').css({width:$(this).width(),marginTop:$(this).outerHeight()*-1});if(element.value)$label.hide();$('<div></div>').append($label).insertAfter($(this));$(this).data("target",$label);if(window.addEventListener){$(this).on("input",function(){if(this.value.trim()==""){$label.show();}else{$label.hide();}});}else{element.attachEvent('onpropertychange',function(event){if(event&&event.propertyName=="value"){if($.trim(element.value)==""){$label.show();}else{$label.hide();}}});}});}
    $(document.body).delegate("a[data-url]","click",function(){var self=$(this);var url=$(this).attr("data-url"),ajax=$(this).attr("data-ajax");if(!url||ajax=="false"||$(this).hasClass("loading"))return;var _ajax=function(eleA){eleA.addClass("loading");$.ajax({url:url,type:"GET",dataType:"json",success:function(json){$.jsonHandle(json);eleA.data("callback")&&eleA.data("callback").call(eleA.get(0),json);eleA.removeClass("loading");},error:function(XMLHttpRequest,textStatus,errorThrown){$.dialog.alert("网络异常，您可以稍后重试。");eleA.removeClass("loading");}});};var _confirm=$(this).attr("data-confirm");if(_confirm){$.dialog.confirm(_confirm,{text:$(this).attr("data-ensure"),func:function(){_ajax(self);}},{text:$(this).attr("data-cancel")});}else{_ajax(self);}});});